### ISSUE TITLE
GET /api/recording-state      

### ISSUE THREAD

**Issue by duongnphong** [zoom/meetingbot-recall-sample#2]
I am trying out to code and i encounter GET /api/recording-state: 400 Bad Request.
Do you know why Im getting this error?

**Comment by tamagoeggo** [comment]
Hey @duongnphong thanks for reaching out! We'd be happy to help you with this.

Are you a current Recall customer? If so, please reach out to us over Slack or email so we can help you debug.
If not, feel free to sign up at [Recall.ai](https://www.recall.ai)!

**Comment by duongnphong** [comment]
Hi, I am currently having recall.ai as pay as you go plan, and I did not get to access to the slack channel yet.
