### ISSUE TITLE
got this problem

### ISSUE THREAD

**Issue by quboqin** [zoom/meetingbot-recall-sample#3]
recall bot start recording https://us05web.zoom.us/j/89245880857?pwd=2tEPjZ4sAWO0t6qqaRF6aS3cUYFYih.1
[1] Recall API returned https://api.recall.ai/api/v1/bot: 401 {"detail":"Invalid token."}

 I don’t know which setting was missed.

**Comment by EdsonMorfin** [comment]
@quboqin Make sure to use the correct endpoint, mine is us-west-2.recall.ai
